#!/bin/bash
# ⚡ Quick Start Guide - Muhammad Waleed Portfolio

echo "🚀 Muhammad Waleed Ur Rehman - Portfolio Setup"
echo "=============================================="
echo ""
echo "📋 Quick Start (3 Steps):"
echo ""
echo "1️⃣  Copy environment template:"
echo "   cp .env.example .env.local"
echo ""
echo "2️⃣  Edit with your credentials:"
echo "   nano .env.local"
echo "   (See ENV_SETUP.md for help getting API keys)"
echo ""
echo "3️⃣  Install and run:"
echo "   npm install"
echo "   npm run dev"
echo ""
echo "🌐 Browser opens at: http://localhost:5173"
echo ""
echo "📚 Documentation:"
echo "   • ENV_SETUP.md              → Setup environment variables"
echo "   • DEPLOYMENT_CHECKLIST.md   → Production deployment guide"
echo "   • COMPLETION_REPORT.md      → What was completed"
echo "   • README.md                 → Project overview"
echo ""
echo "🔐 Security:"
echo "   ✅ .env.local is ignored (never commits)"
echo "   ✅ .env.example is safe to commit"
echo "   ✅ src/config.js manages all secrets"
echo ""
echo "🚀 When ready to deploy:"
echo "   npm run build        # Create production build"
echo "   npm run preview      # Test production locally"
echo "   # Then follow DEPLOYMENT_CHECKLIST.md"
echo ""
echo "✨ All set! Happy coding! ✨"
echo ""
